obj-$(CONFIG_OX820_GMAC) += ox820-gmac.o

ox820-gmac-objs :=	 	ox820_gmac_module.o \
						ox820_gmac_config.o \
						ox820_gmac_phy.o \
						ox820_gmac_interrupt.o \
						ox820_gmac_plain.o \
						ox820_gmac_common.o \
						ox820_gmac_dma.o \
						ox820_gmac_init.o
